name: Bug Report
description: Create a report to see it being fixed
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Describe the issue
      description: A clear and concise description of what the issue is
    validations:
      required: true

  - type: input
    attributes:
      label: Product Version
      description: Version number of the product you're running (latest is not a version)
      placeholder: 1.4.0
    validations:
      required: true

  - type: input
    attributes:
      label: Pterodactyl Panel Version (if applicable)
      description: Version number of your Panel (latest is not a version)
      placeholder: 1.4.0
    validations:
      required: false

  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behaviour
      placeholder: "1. Go to '...'
        2. Click on '....'
        3. Scroll down to '.....'
        4. See error"
    validations:
      required: false

  - type: textarea
    attributes:
      label: Expected Behaviour
      description: What were you expecting to happen?
    validations:
      required: false

  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Information
      description: Add more information about the problem if necessary
    validations:
      required: false
